name: chat_bot_designer
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

# Flutter 2.5.1 • channel stable • https://github.com/flutter/flutter.git
# Framework • revision ffb2ecea52 (7 days ago) • 2021-09-17 15:26:33 -0400
# Engine • revision b3af521a05
# Tools • Dart 2.14.2
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.24
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  google_fonts: ^2.1.0
  stacked: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
